# Generated by Django 5.1.7 on 2025-03-13 04:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WTT_Log',
            fields=[
                ('logID', models.IntegerField(primary_key=True, serialize=False)),
                ('employeeID', models.IntegerField()),
                ('truckID', models.IntegerField()),
                ('trailerID', models.IntegerField(null=True)),
                ('trip', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('load', models.IntegerField()),
                ('height', models.IntegerField()),
                ('defects_en_route', models.CharField(max_length=1000)),
                ('incidents', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=1000)),
                ('pictures', models.CharField(max_length=100)),
                ('declaration', models.IntegerField()),
                ('signature', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'WTT_Log',
            },
        ),
        migrations.CreateModel(
            name='WTT_Log_Inspect_Items',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'WTT_Log_Inspect_Items',
            },
        ),
        migrations.CreateModel(
            name='WTT_Trailer',
            fields=[
                ('trailerID', models.IntegerField(primary_key=True, serialize=False)),
                ('make_model', models.CharField(max_length=60)),
                ('license_plate', models.CharField(max_length=8)),
                ('carrier', models.CharField(max_length=30)),
                ('jurisdiction', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'WTT_Trailer',
            },
        ),
        migrations.CreateModel(
            name='WTT_Truck',
            fields=[
                ('truckID', models.IntegerField(primary_key=True, serialize=False)),
                ('make_model', models.CharField(max_length=60)),
                ('license_plate', models.CharField(max_length=8)),
                ('odometer', models.IntegerField()),
                ('carrier', models.CharField(max_length=30)),
                ('jurisdiction', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'WTT_Truck',
            },
        ),
        migrations.CreateModel(
            name='WTT_Log_Inspect_Det',
            fields=[
                ('detailID', models.AutoField(primary_key=True, serialize=False)),
                ('logID', models.ForeignKey(db_column='logID', on_delete=django.db.models.deletion.CASCADE, to='api.wtt_log')),
                ('itemID', models.ForeignKey(db_column='itemID', on_delete=django.db.models.deletion.CASCADE, to='api.wtt_log_inspect_items')),
            ],
            options={
                'db_table': 'WTT_Log_Inspect_Det',
            },
        ),
        migrations.CreateModel(
            name='WTT_User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeID', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('driver_license', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='wtt_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='wtt_user_permission_set', to='auth.permission')),
            ],
            options={
                'db_table': 'WTT_User',
            },
        ),
    ]
