# Generated by Django 5.1.6 on 2025-02-23 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WTT_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logID', models.IntegerField()),
                ('userID', models.IntegerField()),
                ('truckID', models.IntegerField()),
                ('trailerID', models.IntegerField()),
                ('trip', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('load', models.IntegerField()),
                ('height', models.IntegerField()),
                ('defects_en_route', models.CharField(max_length=1000)),
                ('incidents', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=1000)),
                ('pictures', models.CharField(max_length=100)),
                ('declaration', models.IntegerField()),
                ('signature', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WTT_Log_Inspect_Items',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WTT_Trailer',
            fields=[
                ('trailerID', models.AutoField(primary_key=True, serialize=False)),
                ('make_model', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=8)),
                ('carrier', models.CharField(max_length=30)),
                ('jurisdiction', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WTT_Truck',
            fields=[
                ('truckID', models.AutoField(primary_key=True, serialize=False)),
                ('make_model', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=8)),
                ('odometer', models.IntegerField()),
                ('carrier', models.CharField(max_length=30)),
                ('jurisdiction', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WTT_User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('employeeID', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('driver_license', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WTT_Log_Inspect_Det',
            fields=[
                ('logID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.wtt_log')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wtt_log_inspect_items')),
            ],
        ),
    ]
