# Generated by Django 5.1.6 on 2025-03-11 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='wtt_log',
            old_name='userID',
            new_name='employeeID',
        ),
        migrations.AddField(
            model_name='wtt_log',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='wtt_trailer',
            name='trailerID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wtt_truck',
            name='truckID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wtt_user',
            name='employeeID',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wtt_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
