# Generated by Django 5.1.6 on 2025-03-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_rename_userid_wtt_log_employeeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtt_log',
            name='defects_en_route',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wtt_log',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wtt_log',
            name='incidents',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wtt_log',
            name='load',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wtt_log',
            name='pictures',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wtt_log',
            name='remarks',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
